version: '3'
services:
  app1:
    image: hashicorp/http-echo
    command: -text="Answer from SERVER 1"

  app2:
    image: hashicorp/http-echo
    command: -text="Answer from SERVER 2"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro